name: 02. Understanding GitHub Actions

on:
  push:
    branches: [ main ]
    paths:
      - '**/[0-9]+-understanding-github-actions.yml'

jobs:
  check-bats-version:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
