name: 04. Using templates

on:
  push:
    branches: [ main ]
    paths:
      - '**/[0-9]+-using-templates.yml'

jobs:
  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello CAMs7
