name: 05. Reusing workflows

on:
  push:
    branches: [ main ]
    paths:
      - '**/[0-9]+-reusing-workflows.yml'

jobs:
  call-workflow:
    uses: cams7-tests/github-actions-tests/.github/workflows/05-reusable-workflow.yml@793211b92b8ddd7ec113529cce3e28f88d1e6ca7
    with:
      username: cams7
    secrets:
      token: ${{ secrets.TOKEN }}
