name: 05. Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  show_hello:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello ${{ inputs.username }}, your token is ${{ secrets.token }}
