
name: 08. Workflow syntax

on:
  push:
    branches: [ main ]
    paths:
      - '**[0-9]+-workflow-syntax.yml'
jobs:
  job1:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
  my-job:
    name: My Job
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Print a greeting
        env:
          FIRST_NAME: César
          MIDDLE_NAME: A.
          LAST_NAME: Magalhães
        run: echo Hi there! My name is $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
        
  build:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    strategy:
      matrix:
       include:
         - node-version: 10.x
           site: "prod"
           datacenter: "site-a"
         - node-version: 12.x
           site: "dev"
           datacenter: "site-b"
    steps:
      - name: Echo site details
        env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
        run: echo $SITE $DATACENTER
