
name: 09. Workflow commands

on:
  push:
    branches: [ main ]
    paths:
      - '**/[0-9]+-workflow-commands.yaml'

jobs:
  workflow-command-job:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: disable workflow commands
        run: |
          echo '::warning:: this is a warning'          
          echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
          echo '::warning:: this will NOT be a warning'
          echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
          echo '::warning:: this is a warning again'
          
      - name: Set the value
        id: step_one
        run: |
         echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
