name: 4. Using templates

on:
  push:
    branches: [ main ]
    paths:
      - '**-using-templates.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello CAMs7
