name: 5. Reusing workflows

on:
  push:
    branches: [ main ]

jobs:
  call-workflow:
    uses: cams7-tests/github-actions-tests/.github/workflows/5-reusable-workflow.yml@6b333942af5776e31476070768d90a5d9baa07ca
    with:
      username: cams7
    secrets:
      token: ${{ secrets.TOKEN }}
