
name: 8. Workflow syntax

on:
  push:
    branches: [ main ]
    paths:
      - '**-workflow-syntax.yml'
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          FIRST_NAME: César
          MIDDLE_NAME: A.
          LAST_NAME: Magalhães
        run: |
          echo ${{format('Hi there! My name is {0} {1} {2}.', $FIRST_NAME, $MIDDLE_NAME, $LAST_NAME)}}

