name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: cams7-tests/github-actions-tests/.github/workflows/reusable-workflow-1.yml@82086c7962350dcf9a7c6fd7b9c482357787e953
    with:
      username: cams7
    secrets:
      token: ${{ secrets.TOKEN }}
